[package]
name = "html-view-core"
version = "0.1.0"
edition = "2024"
publish = false
repository.workspace = true

[dependencies]
html.workspace = true
html-view-cfi.workspace = true
html-view-load.workspace = true
html-view-types.workspace = true
kurbo.workspace = true
peniko.workspace = true
unicode-normalization.workspace = true
scraper.workspace = true
smallvec = "1"
